=== AnishSherchan/XML-Music-Store/Development/19030714.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Author Anish Sherchan
uni id: 19030714
-->
<!-- Start of dtd file-->
<!ATTLIST Mystore xmlns:xsi CDATA #REQUIRED xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ELEMENT Mystore (header,Collections,footer)>
<!ELEMENT header (Storedetails,menus)>
<!ELEMENT Storedetails (Storename,address_1,Phone_number,urls)>
<!ELEMENT Storename (#PCDATA)>
<!ELEMENT address_1 (#PCDATA)> 
<!ELEMENT Phone_number (#PCDATA)>
<!ELEMENT urls (#PCDATA)>
<!ELEMENT menus (logo,StoreName+,bars)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT StoreName (#PCDATA)>
<!ATTLIST logo id ID #REQUIRED>
<!ELEMENT bars (home,shop,seprator,listen,download)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT shop (#PCDATA)> 
<!ELEMENT seprator (#PCDATA)>
<!ELEMENT listen (#PCDATA)>
<!ELEMENT download (#PCDATA)>

<!ELEMENT Collections (Featuring,songs)>
<!ELEMENT Featuring (#PCDATA)>
<!ELEMENT songs (Filters+,song+)>
<!ELEMENT footer (#PCDATA)>
<!ATTLIST footer id ID #REQUIRED>
<!ELEMENT Filters (#PCDATA)>
<!ATTLIST Filters id ID #REQUIRED>
<!ELEMENT song (Cover,Head,SongDescription)>
<!ATTLIST song id ID #REQUIRED>
<!ATTLIST song song_id CDATA #REQUIRED>
<!ATTLIST song Listtype CDATA #REQUIRED>
<!ATTLIST song Musictype CDATA #REQUIRED>
<!ATTLIST song beatspermin CDATA #REQUIRED>
<!ATTLIST song rating CDATA #REQUIRED>
<!ATTLIST song views CDATA #IMPLIED>

<!ELEMENT Cover (#PCDATA)>
<!ELEMENT Head (#PCDATA)>
<!ATTLIST Cover id ID #REQUIRED>
<!ATTLIST Head id ID #REQUIRED>

<!ELEMENT SongDescription (Songname,Genre,Director?,Producer,band?,Writer,Singer?,Date,length,MusicVideo?,Tiktok?,Website?)>
<!ATTLIST SongDescription id CDATA #REQUIRED>
<!ELEMENT Songname (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Producer (#PCDATA)>
<!ELEMENT band (#PCDATA)>
<!ELEMENT Writer (#PCDATA)>
<!ELEMENT Singer (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT Website (#PCDATA)>
<!ELEMENT MusicVideo (#PCDATA)>
<!ELEMENT Tiktok (#PCDATA)>

=== AnishSherchan/XML-Music-Store/Development/catalog_19030714.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="catalog_19030714.css" type="text/css"?>
<!DOCTYPE Mystore SYSTEM "./19030714.dtd">
<Mystore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./catalog_19030714.xsd">
    <!-- This is the header part of the xml where shop details along with nav bar are kept with thier respective data-->
    <header>
        <Storedetails><!-- Here we keep information about the Stores whose system we're building-->
            <Storename><!-- All informations regarding Store is kept in Cdata of XML-->
                <![CDATA[ SherchanMusics]]></Storename>
            <address_1><!-- All informations regarding Store is kept in Cdata of XML-->
                <![CDATA[ Samakushi, Kathmandu]]></address_1>
            <Phone_number><!-- All informations regarding Store is kept in Cdata of XML-->
                <![CDATA[ Tel. number: 01-4363678]]></Phone_number>
            <urls><!-- All informations regarding Store is kept in Cdata of XML-->
                <![CDATA[ Website: Sherchanmusic.com]]></urls>
        </Storedetails>
        <menus><!-- Secondary nav for design-->
            <logo id="StoreLogo"></logo><!-- Reusing Logo element and defining attribute called id-->
            <StoreName>SherchanMusics</StoreName>
            <bars><!-- Define some elements for nav bar design-->
                <home>Home</home>
                <shop>Shop</shop>
                <seprator>|</seprator>
                <listen>Listen</listen>
                <download>Download</download>
            </bars>
        </menus>
    </header><!-- End of header-->
    <Collections>
        <Featuring><!-- Image For feature and design--></Featuring><!-- Another parent class for 2 or 3 child classes-->
        <songs><!-- Filrters for Muics-->
            <Filters id="Mostliked">
                <![CDATA[ Most Hits →]]></Filters><!-- Filrters for Muics-->
            <Filters id="Ins">
                <![CDATA[ Instrumental →]]></Filters><!-- Filrters for Muics-->
            <Filters id="popular">
                <![CDATA[ Popular new releases →]]></Filters><!-- Song 1-->
            <song id="Song1" views="1million" song_id="Music1" Listtype="Most-liked" Musictype="InstrumentalandVocal" beatspermin="56" rating="5 stars"><!-- Detail of song-->
                <Cover id="Cover1"></Cover>
                <Head id="Head1">Imagine By John Lennon</Head><!-- Songs Descriptions-->
                <SongDescription id="desc1">
                    <Songname>Name: Imagine</Songname>
                    <Genre>Genre: Pop</Genre>
                    <Producer>Producer: John Lennon</Producer>
                    <Writer>Writer: John Lennon</Writer>
                    <Singer>Singer: John Lennon</Singer>
                    <Date>Release Date: 17 Jan 2004</Date>
                    <length>Length: 4:32</length>
                    <MusicVideo >Music Video: Yes</MusicVideo>
                    <Website>
                        Website: Johnlennon.com
                    </Website>
                </SongDescription>
            </song><!-- Song2-->
            <song id="Song2" song_id="Music2" Listtype="Most-popular" Musictype="Instrumental" beatspermin="90" rating="4 stars"><!-- Detail of song-->
                <Cover id="Cover2"></Cover>
                <Head id="Head2">Stairway to Heaven</Head>
                <SongDescription id="desc2">
                    <Songname>Name: Stairway to heaven</Songname>
                    <Genre>Genre: Rock</Genre>
                    <Producer>Producer: Jimmy Page</Producer>
                    <band>Band: Led Zeppelin</band>
                    <Writer>Writer: Jimmy Page Robert Plant</Writer>
                    <Date>Release Date: 8 November 1971</Date>
                    <length>Length: 8:02</length>
                    <Tiktok>
                        Tiktok: Yes
                    </Tiktok>
                </SongDescription>
            </song><!-- Song number 3-->
            <song id="Song3" song_id="Music3" views="1million" Listtype="Most-Listen" Musictype="Vocal" beatspermin="45" rating="4.4 stars"><!-- Detail of song-->
                <Cover id="Cover3"></Cover>
                <Head id="Head3">Stairway to Heaven</Head>
                <SongDescription id="desc2">
                    <Songname>Name: High Hopes</Songname>
                    <Genre>Genre: Progressive rock</Genre>
                    <Producer>Producer: Bob Ezrin, David Gilmour</Producer>
                    <band>Band: PinkFloyd</band>
                    <Writer>Writer :David Gilmour, Polly Samson</Writer>
                    <Date>Release Date: 17 October 1994</Date>
                    <length>Length: 8:34 (album version)</length>
                    <Website>
                        Website: PinkFloyd.com
                    </Website>
                </SongDescription>
            </song><!-- Song number 4-->
            <song id="Song4" song_id="Music4" Listtype="Most-Liked" Musictype="Instrumental" beatspermin="55" rating="5 stars"><!-- Detail of song-->
                <Cover id="Cover4"></Cover>
                <Head id="Head4">The Man Who Sold The World</Head>
                <SongDescription id="desc2">
                    <Songname>Name: The man who sold the world</Songname>
                    <Genre>Genre: Pop</Genre>
                    <Producer>Producer: Halen Beals</Producer>
                    <band>Band: Nirvana</band>
                    <Writer>killer Heasm</Writer>
                    <Date>Release Date: 17 Jan 2002</Date>
                    <length>Length: 4:32</length>
                    <MusicVideo>Music Video: Yes</MusicVideo>
                </SongDescription>
            </song><!-- Song number 5-->
            <song id="Song5" song_id="Music5" Listtype="Most-Liked" Musictype="Instrumental" beatspermin="55" rating="5 stars"><!-- Detail of song-->
                <Cover id="Cover5"></Cover>
                <Head id="Head5">Hotel California</Head>
                <SongDescription id="desc2">
                    <Songname>Name: Hotel California</Songname>
                    <Genre>Genre: Pop</Genre>
                    <Producer>Producer: Oggy Page</Producer>
                    <band>Band: Egales</band>
                    <Writer>Writer: Jimmy Page</Writer>
                    <Date>Release Date: 8 November 1995</Date>
                    <length>Length: 6:02</length>
                </SongDescription>
            </song><!-- Song number6-->
            <song id="Song6" song_id="Music6" Listtype="Most-popular" Musictype="Instrumental" beatspermin="90" rating="4 stars"><!-- Detail of song-->
                <Cover id="Cover6"></Cover>
                <Head id="Head6">Nothing Else Matter</Head>
                <SongDescription id="desc2">
                    <Songname>Name: Nothing Else Matters</Songname>
                    <Genre>Genre: Rock</Genre>
                    <Producer>Producer: Halen Beals</Producer>
                    <band>Band: Metalica</band>
                    <Writer>Writer: Queens Heasm</Writer>
                    <Date>Release Date: 17 Jan 1994</Date>
                    <length>Length: 4:32</length>
                </SongDescription>
            </song><!-- Song number7-->
            <song id="Song7" song_id="Music7" Listtype="Most-popular" Musictype="Instrumental" beatspermin="90" rating="4 stars"><!-- Detail of song-->
                <Cover id="Cover7"></Cover>
                <Head id="Head7">November Rain</Head>
                <SongDescription id="desc2">
                    <Songname>Song Name: November Rain</Songname>
                    <Genre>Genre: Progressive rock</Genre>
                    <Producer>Producer: Jack Mou</Producer>
                    <band>Band: Guns and Roses</band>
                    <Writer>Writer: Roger Pikks</Writer>
                    <Date>Release Date: 12 September 2000</Date>
                    <length>Length:  8:55</length>
                </SongDescription>
            </song><!-- Song number8-->
            <song id="Song8" song_id="Music8" Listtype="Most-Liked" Musictype="Instrumental" beatspermin="55" rating="5 stars"><!-- Detail of song-->
                <Cover id="Cover8"></Cover>
                <Head id="Head8">Bohemian Rhapsody</Head>
                <SongDescription id="desc2">
                    <Songname>Name: Bohemian Rhapsody</Songname>
                    <Genre>Genre: Rock</Genre>
                    <Producer>Producer: Freedi Mecury</Producer>
                    <band>Band: Queen</band>
                    <Writer>Writer: Freedi Mercury</Writer>
                    <Date>Release Date: 17 Jan 2000</Date>
                    <length>Length: 8:32</length>
                </SongDescription>
            </song><!-- Song number9-->
            <song id="Song9" song_id="Music9" Listtype="Most-liked" Musictype="InstrumentalandVocal" beatspermin="56" rating="5 stars"><!-- Detail of song-->
                <Cover id="Cover9"></Cover>
                <Head id="Head9">Wish you were here</Head>
                <SongDescription id="desc2">
                    <Songname>Name: Wish you were here</Songname>
                    <Genre>Genre: Progressive rock</Genre>
                    <Producer>Producer: David Leland</Producer>
                    <band>Band: Pinkfloyd</band>
                    <Writer>Writer: Roger Waters</Writer>
                    <Date>Release Date: 12 September 1975</Date>
                    <length>Length:  4:55</length>
                    <Website>
                        Website:
                        PinkFloyd.com
                    </Website>
                </SongDescription>
            </song><!-- Song number10-->
            <song id="Song10" song_id="Music10" Listtype="Most-popular" Musictype="Instrumental" beatspermin="90" rating="4 stars"><!-- Detail of song-->
                <Cover id="Cover10"></Cover>
